name: Linter

on:
  push:
    branches: 
    - "main"
  pull_request:
    branches: 
    - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.12"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies [converso]
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --with lint
    - name: Analysing the code with pylint
      run: |
        # poetry run python -m pylint $(git ls-files '*.py') --rcfile=pylint.rc --fail-under=8
        poetry run python -m pylint src --rcfile=pylint.rc --fail-under=7