name: Publish on PyPI

on:
    push:
        tags:
          - 'v*.*.*'
    workflow_dispatch:

jobs:
    check_tag_match:
        name: Check pyproject.toml version matches tag
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2
          
          - name: Install dependencies
            run: |
              python3 -m pip install --upgrade poetry
              poetry install

          - name: Check if tag matches pyproject.toml version
            run: |
              tag=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
              version=$(poetry version -s)
              if [ "$tag" != "v$version" ]; then
                echo "Tag $tag does not match pyproject.toml version v$version"
                exit 1
              fi
  
    build:
        name: Build package
        runs-on: ubuntu-latest
        needs: check_tag_match
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.12.0'

            - name: Install dependencies
              run: |
                  python3 -m pip install --upgrade build

            - name: Build package
              run: python3 -m build

            - name: Store the distribution packages
              uses: actions/upload-artifact@v4
              with:
                name: python-package-distributions
                path: dist/
                
    pypi-publish:
      needs: build
      name: Upload release to PyPI
      runs-on: ubuntu-latest
      environment:
        name: pypi
        url: https://pypi.org/p/converso
      permissions:
        id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
      steps:

        - name: Download all the dists
          uses: actions/download-artifact@v4
          with:
            name: python-package-distributions
            path: dist/
  
        - name: Publish package distributions to PyPI
          uses: pypa/gh-action-pypi-publish@release/v1